t-play: added synchronize workers option (remove time asymmetry bias)
set sync_workers=y in rc file to synchronize workers:
one round = each worker plays one game (same pairing).
next round starts when all games for current round have finished.

this removes time asymmetry between players at the cost of some down time.
everything else is the same: workers can still be added/removed at any time,
they will automatically sync with each other.

otherwise each worker just plays one game after the other as fast as possible,
which maximizes cpu usage but can create significant winrate bias initially if
one player tends to win faster than the other (or if it never resigns but the
other player does !): wins accumulate faster for that player resulting in an
inflated initial winrate that drops over time as losses slowly catch up. it
can take hundreds of games for it to stabilize around the actual winrate.

recommended when testing against opponents like katago which often resigns late
or plays until the end when losing (takes ~600 games to converge).

diff --git a/t-play/autotest/bin/autotest-worker b/t-play/autotest/bin/autotest-worker
--- a/t-play/autotest/bin/autotest-worker
+++ b/t-play/autotest/bin/autotest-worker
@@ -62,6 +62,13 @@ pairing_param() { # Accessor method
 	eval "echo \$$pairvar"
 }
 
+pick_pairing()
+{
+	# XXX RANDOM is bash-specific
+	pair="$((RANDOM % $pairs))"
+	pairid="$(pairing_param $pair id)"
+}
+
 . ./rc
 
 
@@ -71,11 +78,42 @@ if [ "$pairs" = "0" ]; then
 	sleep 1; exit 0
 fi
 
-# XXX RANDOM is bash-specific
-pair="$((RANDOM % $pairs))"
-pairid="$(pairing_param $pair id)"
-echo "Picked pairing #$pair: $pairid"
+if [ "$sync_workers" = "y" ]; then
+	if [ "$clientid" = "$HOSTNAME-1" ]; then
+		# First worker waits until other workers are ready ...
+		msg='Sync workers: Waiting for worker #$i ...'
+		wait_for_other_workers "round_ready" .1 "$msg"
+		echo "Sync workers: Picking pairing for next round."
+		echo ""
 
+		# And picks pairing for next round.
+		pick_pairing
+		echo "$pair"   > c/pair
+		echo "$pairid" > c/pairing
+
+		rm -f c/$clientid/round_done
+		touch c/$clientid/round_ready
+	else
+		# Other workers signal they're ready, wait for others ...
+		touch "c/$clientid/round_ready"
+		msg='Sync workers: Waiting for worker #$i ...'
+		wait_for_other_workers "round_ready" .1 "$msg"
+		echo "Sync workers: Ready for next round."
+		echo ""
+		rm -f c/$clientid/round_done
+
+		# And use common pairing for this round.
+		[ -f "c/pair" ]    || die "Sync workers: c/pair missing !"
+		[ -f "c/pairing" ] || die "Sync workers: c/pairing missing !"
+		pair=`cat c/pair`
+		pairid=`cat c/pairing`
+	fi
+else
+	# Each worker picks its own pairing.
+	pick_pairing
+fi
+
+echo "Picked pairing #$pair: $pairid"
 log "starting game with pairing #$pair: $pairid"
 
 
